// any app specific constants that you don't want to keep in config can go here.
export const SYSTEM_ERROR = 'System error. Please try again later!'
export const CTA_YES = 'Yes'
export const CTA_NO = 'No'
export const CTA_CANCEL = 'Cancel'
export const RES_ERROR = 'Sorry, Something went wrong. Please try again!'
export const EXPIRED = 'You are expired! Try to login again'
export const INVALID_EMAIL = 'Invalid Email Address!'
export const INVALID_MATCH = 'Password does not match!'
export const INVALID_LENGTH = 'Password should be longer than 8 characters'
export const NOT_FILL = 'Fill all fields'
